services:

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/riego
    depends_on:
      - postgres

volumes:
  postgres_data: